### ISSUE TITLE
Cannot compile with dmd 2.068.0 in x86_64

### ISSUE THREAD

**Issue by albatr0z** [callumenator/dabble#9]
This are the message when trying to build with the dmd 2.068.0:

 dub run
## Warning for package dabble

The following compiler flags have been specified in the package description
file. They are handled by DUB and direct use in packages is discouraged.
Alternatively, you can set the DFLAGS environment variable to pass custom flags
to the compiler, or use one of the suggestions below:

-release: Call dub with --build=release

WARNING: A deprecated branch based version specification is used for the dependency pegged. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
Performing "debug" build using dmd for x86_64.
pegged ~master: target for configuration "library" is up to date.
dabble ~master: building configuration "application"...
/usr/include/dmd/phobos/std/container/rbtree.d(823,25): Error: function modulecache.cacheComparitor (CacheEntry\* a, CacheEntry\* b) is not callable using argument types (inout(CacheEntry_), CacheEntry_)
/usr/include/dmd/phobos/std/container/rbtree.d(825,30): Error: function modulecache.cacheComparitor (CacheEntry\* a, CacheEntry\* b) is not callable using argument types (CacheEntry_, inout(CacheEntry_))
src/DCD/modulecache.d(230,9): Error: template instance std.container.rbtree.RedBlackTree!(CacheEntry_, cacheComparitor, false) error instantiating
src/dabble/defs.d(46,12): Error: no property 'clear' for type 'Type_[string]'
src/dabble/defs.d(47,13): Error: no property 'clear' for type 'Var[]'
src/dabble/defs.d(48,14): Error: no property 'clear' for type 'Decl[]'
src/dabble/defs.d(49,14): Error: no property 'clear' for type 'Vtbl[]'
src/dabble/meta.d(20,12): Deprecation: function std.process.system is deprecated - Please use wait(spawnShell(command)) or executeShell(command) instead
src/dabble/meta.d(124,26): Error: no property 'clear' for type 'SharedLib[]'
src/dabble/meta.d(174,27): Error: no property 'clear' for type 'string'
src/dabble/meta.d(191,12): Error: no property 'clear' for type 'string'
src/dabble/parser.d(63,15): Error: no property 'clear' for type 'Tuple!(ulong, ulong, string)[]'
src/dabble/parser.d(64,16): Error: no property 'clear' for type 'Tuple!(ulong, ulong)[]'
src/dabble/parser.d(172,18): Error: no property 'clear' for type 'string[]'
src/dabble/parser.d(173,19): Error: no property 'clear' for type 'string[][]'
src/dabble/repl.d(205,12): Error: no property 'clear' for type 'Tuple!(string, "stage", long, "msecs")[]'
src/dabble/repl.d(222,14): Error: no property 'clear' for type 'string'
src/dabble/repl.d(231,14): Error: no property 'clear' for type 'string'
src/dabble/repl.d(277,16): Error: no property 'clear' for type 'Entry[]'
src/dabble/repl.d(278,14): Error: no property 'clear' for type 'Entry[]'
dmd failed with exit code 1.
