### ISSUE TITLE
Cannot compile with dmd 2.067.0

### ISSUE THREAD

**Issue by pravic** [callumenator/dabble#6]
DUB version 0.9.23, built on Apr  6 2015
DMD32 D Compiler v2.067.0

```
src\dabble\defs.d(68): Error: template instance std.array.array!(FilterResult!(__lambda1, Var[])) error instantiating
src\dabble\defs.d(77): Error: template instance std.array.array!(FilterResult!(__lambda2, Var[])) error instantiating
src\dabble\repl.d(550): Error: no property 'name' for type 'string'
src\dabble\repl.d(750): Error: module std.datetime import 'getTimes' not found
```

**Comment by pezipink** [comment]
same here, I was using a slightly older version of the compiler (0.63?) and it did not build with a different error. I have upgraded to 067.0 and get the same errors as above.

**Comment by callumenator** [comment]
Yeah it will take a little time to fix sorry, a few dependencies have changed since I last built it.

**Comment by pezipink** [comment]
Cool. I had a go at sorting it out myself, but some of it is beyond my current D capabilities.  Looks awesome though, look forward to giving it a go!

**Comment by callumenator** [comment]
Ok so a quick fix is checked in, let me know if there are issues. There are lots of deprecation messages still. It also seems like dmd 2.067 compiles a bit slower than the last time I played with this, there is noticeable lag.
